accountancy/urls.py
from django.conf.urls import patterns, include, url

from .views import AccountListView, AccountDetailView, AccountCreateView, AccountUpdateView, AccountList, BookListView, BookDetailView, BookCreateView, BookUpdateView


urlpatterns = patterns(
    'accountancy.views',

    # Account
    url(r'^account/$',
        AccountListView.as_view(),
        name='account_list'),

    url(r'^account/view/(?P<pk>[\w-]+)$',
        AccountDetailView.as_view(),
        name='account_detail'),

    url(r'^account/create$',
        AccountCreateView.as_view(),
        name='account_create'),

    url(r'^account/update/(?P<pk>[\w-]+)$',
        AccountUpdateView.as_view(),
        name='account_update'),

    url(r'^rest/account/$',
        AccountList.as_view(),
        name='account_rest_list'),

    # Book
    url(r'^book/$',
        BookListView.as_view(),
        name='book_list'),

    url(r'^book/view/(?P<pk>[\w-]+)$',
        BookDetailView.as_view(),
        name='book_detail'),

    url(r'^book/create$',
        BookCreateView.as_view(),
        name='book_create'),

    url(r'^book/update/(?P<pk>[\w-]+)$',
        BookUpdateView.as_view(),
        name='book_update'),
)

simple/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(
    '',
    url(r'^users/', include('users.urls')),
    url(r'^accountancy/', include('accountancy.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^login$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout$', 'django.contrib.auth.views.logout', {'template_name': 'registration/login.html'}),    
)

users/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'users.views',
    url(r'^landscape$', 'landscape', name='landscape'),
)

accountancy/models.py
from django.db import models
from django.utils.translation import ugettext as _


ROOT = 'ROOT'
ASSETS = 'ASSE'
LIABILITIES = 'LIAB'
OBLIGATIONS = 'OBLI'

ACCOUNT_TYPE_CHOICES = (
    (ROOT, _('account_type_root')),
    (ASSETS, _('account_type_assets')),
    (LIABILITIES, _('account_type_liabilities')),
    (OBLIGATIONS, _('account_type_obligations')),
)


class Account(models.Model):
    description = models.CharField(max_length=128,
                                   verbose_name=_('account_description'))
    account_type = models.CharField(max_length=4,
                                    choices=ACCOUNT_TYPE_CHOICES,
                                    verbose_name=_('account_type'))
    parent = models.ForeignKey('self', null=True, blank=True,
                               related_name='childs',
                               verbose_name=_('account_parent'))

    class Meta():
        verbose_name = _('account')
        verbose_name_plural = _('account_plural')

    def __str__(self):
        return u'%s' % self.description

    def __unicode__(self):
        return u'%s' % self.description
    

class Book(models.Model):
    description = models.CharField(max_length=128,
                                   verbose_name=_('book_description'))
    valid_from = models.DateField(verbose_name=_('book_valid_from'))
    valid_to = models.DateField(verbose_name=_('book_valid_to'))
    root = models.ForeignKey(Account, null=False, blank=False,
                             verbose_name=_('book_root'))

    class Meta():
        verbose_name = _('book')
        verbose_name_plural = _('book_plural')

    def __str__(self):
        return u'%s' % self.description

    def __unicode__(self):
        return u'%s' % self.description

users/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext as _


ADMINISTRATOR = 'ADMIN'
REGULAR = 'REGUL'
SUPERVISOR = 'SUPER'
AUDITOR = 'AUDIT'

USER_TYPE_CHOICES = (
    (ADMINISTRATOR, _('type_Administrator')),
    (REGULAR, _('type_Regular')),
    (SUPERVISOR, _('type_Supervisor')),
    (AUDITOR, _('type_Auditor')),
)


class CustomUser(models.Model):
    user = models.OneToOneField(User)
    user_type = models.CharField(max_length=5,
                                 choices=USER_TYPE_CHOICES,
                                 default=REGULAR,
                                 verbose_name=_('custom_user_user_type'))

    class Meta():
        verbose_name = _('custom_user')
        verbose_name_plural = _('custom_user_plural')

    def __str__(self):
        return "%s %s (%s)" % (self.user.first_name, self.user.last_name, self.user_type)

accountancy/forms.py
from django.forms import DateField, ModelForm, ValidationError
from django.forms.widgets import DateInput

from .models import Account, Book


class CustomDateInput(DateInput):
    input_type = 'date'


class AccountForm(ModelForm):
    class Meta:
        model = Account
        fields = ['account_type', 'parent', 'description']
        exclude = ['root']

    def clean(self):
        cleaned_data = super(AccountForm, self).clean()
        account_type = cleaned_data.get('account_type')
        parent = cleaned_data.get('parent')

        if account_type:
            if account_type == 'ROOT':
                if parent:
                    raise ValidationError('El tipo raiz no permite padre',
                                          code='error1')
            else:
                if not parent:
                    raise ValidationError('Debe indicar una cuenta padre',
                                          code='error2')


class BookForm(ModelForm):
    valid_from = DateField(widget=CustomDateInput())
    valid_to = DateField(widget=CustomDateInput())

    class Meta:
        model = Book
        fields = ['description', 'valid_from', 'valid_to']

    def save(self, commit=True, *args, **kwargs):
        instance = super(BookForm, self).save(commit=False, *args, **kwargs)
        if not hasattr(instance, 'root'):
            root = Account(account_type='ROOT', description='Root account')
            root.save()
            instance.root = root
        if commit:
            instance.save()
        return instance

accountancy/views.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView

from rest_framework.views import APIView
from rest_framework.response import Response

from .forms import AccountForm, BookForm
from .models import Account, Book
from .serializers import AccountSerializer


class AccountListView(ListView):
    model = Account


class AccountDetailView(DetailView):
    model = Account


class AccountCreateView(CreateView):
    model = Account
    fields = ['account_type', 'parent', 'description']
    form_class = AccountForm

    def get_success_url(self):
        return reverse_lazy('account_detail', args=[self.object.pk])


class AccountUpdateView(UpdateView):
    model = Account
    fields = ['account_type', 'parent', 'description']

    def get_success_url(self):
        return reverse_lazy('account_detail', args=[self.object.pk])


class AccountList(APIView):
    """
    List all accounts, or create a new account.
    """
    def get(self, request, format=None):
        accounts = Account.objects.all()
        serializer = AccountSerializer(accounts, many=True)
        return Response(serializer.data)


class BookListView(ListView):
    model = Book


class BookDetailView(DetailView):
    model = Book


class BookCreateView(CreateView):
    model = Book
    fields = ['description', 'valid_from', 'valid_to']
    form_class = BookForm

    def get_success_url(self):
        return reverse_lazy('book_detail', args=[self.object.pk])


class BookUpdateView(UpdateView):
    model = Book
    fields = ['description', 'valid_from', 'valid_to']
    form_class = BookForm

    def get_success_url(self):
        return reverse_lazy('book_detail', args=[self.object.pk])

users/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .models import CustomUser


@login_required
def landscape(request):
    u = CustomUser.objects.get(user=request.user)
    return render(request, 'users/landscape.html', {'user': u})

templates/accountancy/account_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}
{% block body %}
{% if object.childs.count > 0 %}
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">Cuenta</div>
    <div class="panel-body">
      <p class="bg-danger">
	El objeto {{ object }} tiene hijos, no se puede eliminar.
      </p>
    </div>
  </div>
</div>
{% else %}
<form action="" method="post">
  {% csrf_token %}
  <p>{% trans "account_delete_confirm_message" %} {{ object }}?</p>
  <input type="submit" value="{% trans "confirm" %}" class="btn btn-primary" />
</form>
{% endif %}
{% endblock %}

templates/accountancy/account_detail.html
{% extends "base.html" %}
{% block body %}
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">Cuenta</div>
    <div class="panel-body">
      <ul>
	<li>Id: {{ object.id }}</li>
	<li>Descripción: {{ object.description }}</li>
	<li>Tipo: {{ object.get_account_type_display }}</li>
      </ul>
    </div>
  </div>
</div>
{% endblock %}

templates/accountancy/account_form.html
{% extends "base.html" %}
{% load bootstrap %}
{% load i18n %}
{% block body %}
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">Crear cuenta</div>
    <div class="panel-body">
      <form action="" method="post" role="form">
	{% csrf_token %}
	{{ form | bootstrap }}
	<input type="submit" class="btn btn-primary" value="{% trans "create_new" %}" />
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/accountancy/account_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block styles %}
<link href="{% static "css/tree.css" %}" rel="stylesheet" media="screen">
{% endblock %}
{% block scripts %}
<script src="{%  static "js/tree.js" %}"></script>
{% endblock %}
{% block body %}
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">Cuentas</div>
    <div class="panel-body">
      <ul>
	{% for account in object_list %}
	  {% if account.account_type == 'ROOT' %}
	    <div class="tree well">
              {% with account=account template_name="accountancy/account_tree.html" %}
                {% include template_name %}
              {% endwith %}
	    </div>
	  {% endif %}
	{% empty %}
	<li>No accounts yet.</li>
	{% endfor %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

templates/accountancy/account_tree.html
<ul>
  <li>
    <span>{{ account.description }}</span>
    {% for a in account.childs.all %}
      {% with account=a template_name="accountancy/account_tree.html" %}
        {% include template_name%}
      {% endwith %}
    {% endfor %}
  </li>
</ul>

templates/accountancy/book_detail.html
{% extends "base.html" %}
{% block body %}
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">Libro</div>
    <div class="panel-body">
      <ul>
	<li>Id: {{ object.id }}</li>
	<li>Descripción: {{ object.description }}</li>
	<li>Válido desde: {{ object.valid_from }}</li>
	<li>Válido hasta: {{ object.valid_to }}</li>
	<li>Cuenta raiz: {{ object.root.id }} {{ object.root }}</li>
      </ul>
    </div>
  </div>
</div>
{% endblock %}

templates/accountancy/book_form.html
{% extends "base.html" %}
{% load bootstrap %}
{% load i18n %}
{% block body %}
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">Crear libro</div>
    <div class="panel-body">
      <form action="" method="post" role="form">
	{% csrf_token %}
	{{ form | bootstrap }}
	<input type="submit" class="btn btn-primary" value="{% trans "create_new" %}" />
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/accountancy/book_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block styles %}
{% endblock %}
{% block body %}
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">Cuentas</div>
    <div class="panel-body">
      <ul>
	{% for book in object_list %}
	<li>{{ book }}</li>
	{% empty %}
	<li>No books yet.</li>
	{% endfor %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!doctype html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet" media="screen">
    {% block styles %}{% endblock %}
  </head>
  <body>
    {% block body %}{% endblock %}
    <script src="{%  static "js/jquery-2.1.1.min.js" %}"></script>
    <script src="{%  static "js/bootstrap.min.js" %}"></script>
    {% block scripts %}{% endblock %}
  </body>
</html>

templates/users/landscape.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% block title %}{% trans "landscape_title" %}{% endblock %}
{% block body %}

{% include "users/navbar.html" %}
Welcome {{ user.user.first_name }} {{ user.user.last_name }}
<br>
Sos del tipo {{ user.user_type }}
<hr>
{% endblock %}

templates/users/navbar.html
{% load i18n %}
<!-- Static navbar -->
<div class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Tickets</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Tickets</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li class="dropdown-header">Nav header</li>
            <li><a href="#">Separated link</a></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="../navbar-static-top/">{% trans "landscape_settings" %}</a></li>
        <li><a href="../navbar-fixed-top/">{% trans "landscape_mysettings" %}</a></li>
        <li><a href="/logout">{% trans "logout" %}</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</div>